site_name: bareASGI-prometheus
site_description: Prometheus metrics for bareASGI
site_dir: docs

docs_dir: documentation

repo_name: rob-blackbourn/bareASGI-prometheus
repo_url: https://github.com/rob-blackbourn/bareASGI-prometheus
edit_uri: ""

theme:
    name: 'material'
    logo: images/peach.svg

nav:
  - index.md
  - User Guide:
    - user-guide/installation.md
    - user-guide/usage.md
  - API:
    - bareasgi_prometheus: api/bareasgi_prometheus.md
  
markdown_extensions:
  - admonition
  - codehilite
  - jetblack_markdown.autodoc:
      class_from_init: true
      ignore_dunder: true
      ignore_private: true
      ignore_all: false
      ignore_inherited: false
      follow_module_tree: false
      prefer_docstring: true
      template_folder: templates

extra_css:
    - css/custom.css
