[tool.poetry]
name = "bareASGI-prometheus"
version = "3.3.0"
description = "Prometheus metrics for bareASGI"
authors = ["Rob Blackbourn <rob.blackbourn@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "bareasgi_prometheus" },
]
repository = "https://github.com/rob-blackbourn/bareASGI-prometheus"

[tool.poetry.dependencies]
python = "^3.7"
baretypes = "^3.0.5"
bareutils = "^3.1"
bareASGI = "^3.0"
prometheus_client = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-asyncio "^0.10"
pytest-runner = "^5.1"
uvicorn = "^0.9"
hypercorn = "^0.9"
Sphinx = "^1.8"
sphinxcontrib-websupport = "^1.1"
uvloop = "^0.13.0"
pylint = "^2.3"
mypy = "^0.720.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
